"""empty message

Revision ID: 02381534c529
Revises: f7e302692d50
Create Date: 2018-06-01 11:04:26.841594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02381534c529'
down_revision = 'f7e302692d50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('closest_to_bull', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'closest_to_bull')
    # ### end Alembic commands ###
