"""empty message

Revision ID: 037f62122689
Revises: 37ac7bd96038
Create Date: 2019-01-15 19:39:37.182051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '037f62122689'
down_revision = '37ac7bd96038'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=25), nullable=True),
    sa.Column('sigma_x', sa.Integer(), nullable=True),
    sa.Column('sigma_y', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('games', sa.Column('bot_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'games', 'bots', ['bot_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'games', type_='foreignkey')
    op.drop_column('games', 'bot_id')
    op.drop_table('bots')
    # ### end Alembic commands ###
