"""empty message

Revision ID: 077302ba7c7e
Revises: 8cfc90667c26
Create Date: 2018-06-19 11:19:03.939123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '077302ba7c7e'
down_revision = '8cfc90667c26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('caller', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'caller')
    # ### end Alembic commands ###
