"""empty message

Revision ID: 09732e487d22
Revises: 6e84670c6704
Create Date: 2020-04-01 18:03:04.851515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09732e487d22'
down_revision = '6e84670c6704'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_games_player1'), 'games', ['player1'], unique=False)
    op.create_index(op.f('ix_games_player2'), 'games', ['player2'], unique=False)
    op.create_index(op.f('ix_games_status'), 'games', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_games_status'), table_name='games')
    op.drop_index(op.f('ix_games_player2'), table_name='games')
    op.drop_index(op.f('ix_games_player1'), table_name='games')
    # ### end Alembic commands ###
