"""empty message

Revision ID: 0990320b48fe
Revises: ac29765971b6
Create Date: 2020-04-10 14:12:56.795059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0990320b48fe'
down_revision = 'ac29765971b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('webcam_settings',
    sa.Column('user', sa.Integer(), nullable=False),
    sa.Column('activated', sa.Boolean(), nullable=True),
    sa.Column('stream_consent', sa.Boolean(), nullable=True),
    sa.Column('flip_preview', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user'], ['users.id'], name=op.f('fk_webcam_settings_user_users')),
    sa.PrimaryKeyConstraint('user', name=op.f('pk_webcam_settings'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('webcam_settings')
    # ### end Alembic commands ###
