"""empty message

Revision ID: 0f8102f27175
Revises: d376c386d25b
Create Date: 2020-04-03 13:05:54.969870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f8102f27175'
down_revision = 'd376c386d25b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_settings', sa.Column('checkout_suggestions', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_settings', 'checkout_suggestions')
    # ### end Alembic commands ###
