"""empty message

Revision ID: 1009b27a5033
Revises: e38a7a6adc5a
Create Date: 2020-04-19 14:50:32.094479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1009b27a5033'
down_revision = 'e38a7a6adc5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cricket_presettings',
    sa.Column('user', sa.Integer(), nullable=False),
    sa.Column('bo_sets', sa.Integer(), nullable=True),
    sa.Column('bo_legs', sa.Integer(), nullable=True),
    sa.Column('two_clear_legs', sa.Boolean(), nullable=True),
    sa.Column('starter', sa.String(length=25), nullable=True),
    sa.Column('opponent_type', sa.String(length=10), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('public_challenge', sa.Boolean(), nullable=True),
    sa.Column('webcam', sa.Boolean(), nullable=True),
    sa.Column('score_input_delay', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user'], ['users.id'], name=op.f('fk_cricket_presettings_user_users')),
    sa.PrimaryKeyConstraint('user', name=op.f('pk_cricket_presettings'))
    )
    op.add_column('games', sa.Column('variant', sa.String(length=50), nullable=True))
    op.add_column('games_cricket', sa.Column('variant', sa.String(length=50), nullable=True))
    op.drop_column('games_cricket', 'type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games_cricket', sa.Column('type', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('games_cricket', 'variant')
    op.drop_column('games', 'variant')
    op.drop_table('cricket_presettings')
    # ### end Alembic commands ###
