"""empty message

Revision ID: 100d0a3abe51
Revises: 128bdbddde78
Create Date: 2020-04-04 13:04:46.233572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '100d0a3abe51'
down_revision = '128bdbddde78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_settings', sa.Column('show_average_in_chat_list', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_settings', 'show_average_in_chat_list')
    # ### end Alembic commands ###
