"""empty message

Revision ID: 13ddbcd2b390
Revises: 326545465b38
Create Date: 2018-06-01 15:28:43.922096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13ddbcd2b390'
down_revision = '326545465b38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('opponent_type', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'opponent_type')
    # ### end Alembic commands ###
