"""empty message

Revision ID: 1507255054e5
Revises: 76510d9e9453
Create Date: 2021-02-10 21:27:24.320584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1507255054e5'
down_revision = '76510d9e9453'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_games_all_janus_room', 'games_all', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_games_all_janus_room', 'games_all', ['janus_room'])
    # ### end Alembic commands ###
