"""empty message

Revision ID: 19fd30207669
Revises: 2afcf55e7188
Create Date: 2020-03-24 15:43:28.675966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19fd30207669'
down_revision = '2afcf55e7188'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('socket_connections', sa.Column('last_reset', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('socket_connections', 'last_reset')
    # ### end Alembic commands ###
