"""empty message

Revision ID: 21ff805809b7
Revises: 7a5db6a443fe
Create Date: 2020-04-24 13:03:26.013960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21ff805809b7'
down_revision = '7a5db6a443fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games_cricket', sa.Column('undo_possible', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games_cricket', 'undo_possible')
    # ### end Alembic commands ###
