"""empty message

Revision ID: 2e67bce630bc
Revises: 8838fe74befc
Create Date: 2018-06-09 19:12:51.818183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e67bce630bc'
down_revision = '8838fe74befc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
