"""empty message

Revision ID: 3057cf5dd2be
Revises: d186a43f11cf
Create Date: 2020-03-25 12:01:56.486160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3057cf5dd2be'
down_revision = 'd186a43f11cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_user_statistic_user'), 'user_statistic', ['user'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_user_statistic_user'), 'user_statistic', type_='unique')
    # ### end Alembic commands ###
