"""empty message

Revision ID: 326545465b38
Revises: 02381534c529
Create Date: 2018-06-01 11:38:34.429972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '326545465b38'
down_revision = '02381534c529'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('closest_to_bull_json', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'closest_to_bull_json')
    # ### end Alembic commands ###
