"""empty message

Revision ID: 347a1c54005d
Revises: 09732e487d22
Create Date: 2020-04-01 18:04:16.742350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '347a1c54005d'
down_revision = '09732e487d22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_chatmessages_timestamp'), 'chatmessages', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chatmessages_timestamp'), table_name='chatmessages')
    # ### end Alembic commands ###
