"""empty message

Revision ID: 3767876f060a
Revises: 7e00085d7007
Create Date: 2020-03-30 16:17:15.492149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3767876f060a'
down_revision = '7e00085d7007'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tournaments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creator', sa.Integer(), nullable=True),
    sa.Column('hashid', sa.String(length=10), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('public', sa.Boolean(), nullable=True),
    sa.Column('external_link', sa.String(length=120), nullable=True),
    sa.Column('start_timestamp', sa.DateTime(), nullable=True),
    sa.Column('creation_timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['creator'], ['users.id'], name=op.f('fk_tournaments_creator_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tournaments')),
    sa.UniqueConstraint('hashid', name=op.f('uq_tournaments_hashid'))
    )
    op.add_column('users', sa.Column('registration_timestamp', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'registration_timestamp')
    op.drop_table('tournaments')
    # ### end Alembic commands ###
