"""empty message

Revision ID: 377228bb1f36
Revises: d28336dba58f
Create Date: 2020-04-17 21:14:34.898834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '377228bb1f36'
down_revision = 'd28336dba58f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('callers',
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('display_name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('name', name=op.f('pk_callers'))
    )
    op.add_column('user_settings', sa.Column('caller', sa.String(length=30), nullable=True))
    op.create_foreign_key(op.f('fk_user_settings_caller_callers'), 'user_settings', 'callers', ['caller'], ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_user_settings_caller_callers'), 'user_settings', type_='foreignkey')
    op.drop_column('user_settings', 'caller')
    op.drop_table('callers')
    # ### end Alembic commands ###
