"""empty message

Revision ID: 37ac7bd96038
Revises: d45788d90259
Create Date: 2019-01-10 15:13:32.193266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37ac7bd96038'
down_revision = 'd45788d90259'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chatmessages_ingame',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_hashid', sa.String(length=10), nullable=False),
    sa.Column('author', sa.Integer(), nullable=True),
    sa.Column('message', sa.String(length=500), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id', 'game_hashid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chatmessages_ingame')
    # ### end Alembic commands ###
