"""empty message

Revision ID: 3852985df9fd
Revises: 4f6b5fef662c
Create Date: 2018-05-17 09:42:54.361470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3852985df9fd'
down_revision = '4f6b5fef662c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('games', 'player1',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('games', 'player2',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('games', 'player2',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('games', 'player1',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
