"""empty message

Revision ID: 39073935c873
Revises: b02d504627a2
Create Date: 2018-05-18 12:10:09.253475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39073935c873'
down_revision = 'b02d504627a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('games', 'type',
               existing_type=sa.VARCHAR(length=4),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('games', 'type',
               existing_type=sa.VARCHAR(length=4),
               nullable=False)
    # ### end Alembic commands ###
