"""empty message

Revision ID: 3f1057c5e16e
Revises: 7df519023d38
Create Date: 2020-03-28 17:05:42.003601

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f1057c5e16e'
down_revision = '7df519023d38'
branch_labels = None
depends_on = None


def upgrade():
    op.execute('ALTER TABLE chatmessages_ingame DROP CONSTRAINT chatmessages_ingame_pkey CASCADE')
    # Re-create the primary key constraint
    op.create_primary_key('chatmessages_ingame_pkey', 'chatmessages_ingame', ['id'])
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chatmessages_ingame', 'game_hashid',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chatmessages_ingame', 'game_hashid',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    # ### end Alembic commands ###
