"""empty message

Revision ID: 3fdf99bb6314
Revises: e9bce18a545f
Create Date: 2018-05-17 09:30:39.298032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fdf99bb6314'
down_revision = 'e9bce18a545f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('games', 'bo_legs',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('games', 'bo_sets',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('games', 'bo_sets',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('games', 'bo_legs',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
