"""empty message

Revision ID: 46527561d02c
Revises: ed681f762e01
Create Date: 2020-04-06 13:55:34.670190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46527561d02c'
down_revision = 'ed681f762e01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tournament_banned_players_association',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], name=op.f('fk_tournament_banned_players_association_tournament_id_tournaments')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_tournament_banned_players_association_user_id_users')),
    sa.PrimaryKeyConstraint('user_id', 'tournament_id', name=op.f('pk_tournament_banned_players_association'))
    )
    op.add_column('tournaments', sa.Column('registration_open', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tournaments', 'registration_open')
    op.drop_table('tournament_banned_players_association')
    # ### end Alembic commands ###
