"""empty message

Revision ID: 4b8ff246769c
Revises: c0a31cca0e11
Create Date: 2020-04-03 10:07:49.861180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b8ff246769c'
down_revision = 'c0a31cca0e11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hashid', sa.String(length=10), nullable=True))
    op.create_index(op.f('ix_users_hashid'), 'users', ['hashid'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_hashid'), table_name='users')
    op.drop_column('users', 'hashid')
    # ### end Alembic commands ###
