"""empty message

Revision ID: 4cdc7d622e75
Revises: abaef29d6ab4
Create Date: 2020-03-29 19:51:19.360022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cdc7d622e75'
down_revision = 'abaef29d6ab4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('username_changes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.Column('old_name', sa.String(length=25), nullable=True),
    sa.Column('new_name', sa.String(length=25), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_username_changes'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('username_changes')
    # ### end Alembic commands ###
