"""empty message

Revision ID: 4ea89fe9b402
Revises: d3fb9c0399cc
Create Date: 2018-05-16 23:36:55.820147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ea89fe9b402'
down_revision = 'd3fb9c0399cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('type', sa.String(length=4), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'type')
    # ### end Alembic commands ###
