"""empty message

Revision ID: 4f6b5fef662c
Revises: 3fdf99bb6314
Create Date: 2018-05-17 09:39:02.670429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f6b5fef662c'
down_revision = '3fdf99bb6314'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('p1_next_turn', sa.Boolean(), nullable=True))
    op.alter_column('games', 'type',
               existing_type=sa.VARCHAR(length=4),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('games', 'type',
               existing_type=sa.VARCHAR(length=4),
               nullable=True)
    op.drop_column('games', 'p1_next_turn')
    # ### end Alembic commands ###
