"""empty message

Revision ID: 532096580f7b
Revises: d98eccfc90ca
Create Date: 2020-05-11 14:54:56.760154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '532096580f7b'
down_revision = 'd98eccfc90ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tournament_stages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tournament_id', sa.Integer(), nullable=True),
    sa.Column('format', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], name=op.f('fk_tournament_stages_tournament_id_tournaments')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tournament_stages'))
    )
    op.create_table('tournament_stage_rounds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stage_id', sa.Integer(), nullable=True),
    sa.Column('variant', sa.String(length=50), nullable=True),
    sa.Column('bo_sets', sa.Integer(), nullable=False),
    sa.Column('bo_legs', sa.Integer(), nullable=False),
    sa.Column('two_clear_legs', sa.Boolean(), nullable=True),
    sa.Column('starter', sa.String(length=30), nullable=True),
    sa.Column('score_input_delay', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['stage_id'], ['tournament_stages.id'], name=op.f('fk_tournament_stage_rounds_stage_id_tournament_stages')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tournament_stage_rounds'))
    )
    op.add_column('games', sa.Column('tournament_round_id', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('tournament_stage_game_bracket_id', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('tournament_stage_game_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_games_tournament_round_id_tournament_stage_rounds'), 'games', 'tournament_stage_rounds', ['tournament_round_id'], ['id'])
    op.add_column('games_cricket', sa.Column('tournament_round_id', sa.Integer(), nullable=True))
    op.add_column('games_cricket', sa.Column('tournament_stage_game_bracket_id', sa.Integer(), nullable=True))
    op.add_column('games_cricket', sa.Column('tournament_stage_game_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_games_cricket_tournament_round_id_tournament_stage_rounds'), 'games_cricket', 'tournament_stage_rounds', ['tournament_round_id'], ['id'])
    op.add_column('tournaments', sa.Column('managed_externally', sa.Boolean(), nullable=True))
    op.add_column('tournaments', sa.Column('maximum_players', sa.Integer(), nullable=True))
    op.add_column('tournaments', sa.Column('registration_apply', sa.Boolean(), nullable=True))
    op.add_column('tournaments', sa.Column('status', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tournaments', 'status')
    op.drop_column('tournaments', 'registration_apply')
    op.drop_column('tournaments', 'maximum_players')
    op.drop_column('tournaments', 'managed_externally')
    op.drop_constraint(op.f('fk_games_cricket_tournament_round_id_tournament_stage_rounds'), 'games_cricket', type_='foreignkey')
    op.drop_column('games_cricket', 'tournament_stage_game_id')
    op.drop_column('games_cricket', 'tournament_stage_game_bracket_id')
    op.drop_column('games_cricket', 'tournament_round_id')
    op.drop_constraint(op.f('fk_games_tournament_round_id_tournament_stage_rounds'), 'games', type_='foreignkey')
    op.drop_column('games', 'tournament_stage_game_id')
    op.drop_column('games', 'tournament_stage_game_bracket_id')
    op.drop_column('games', 'tournament_round_id')
    op.drop_table('tournament_stage_rounds')
    op.drop_table('tournament_stages')
    # ### end Alembic commands ###
