"""empty message

Revision ID: 594808340e89
Revises: 27b7107cdecc
Create Date: 2020-05-16 10:05:02.889809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '594808340e89'
down_revision = '27b7107cdecc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tournament_stage_rounds_x01',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Integer(), nullable=True),
    sa.Column('in_mode', sa.String(length=15), nullable=True),
    sa.Column('out_mode', sa.String(length=15), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['tournament_stage_rounds.id'], name=op.f('fk_tournament_stage_rounds_x01_id_tournament_stage_rounds')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tournament_stage_rounds_x01'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tournament_stage_rounds_x01')
    # ### end Alembic commands ###
