"""empty message

Revision ID: 654eac861775
Revises: 1009b27a5033
Create Date: 2020-04-19 15:51:46.367494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '654eac861775'
down_revision = '1009b27a5033'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games_cricket', sa.Column('p1_score', sa.Integer(), nullable=True))
    op.add_column('games_cricket', sa.Column('p2_score', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games_cricket', 'p2_score')
    op.drop_column('games_cricket', 'p1_score')
    # ### end Alembic commands ###
