"""empty message

Revision ID: 6b9bed83861a
Revises: 70e01d100867
Create Date: 2020-04-13 16:47:18.416458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b9bed83861a'
down_revision = '70e01d100867'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('x01_presettings', sa.Column('webcam', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('x01_presettings', 'webcam')
    # ### end Alembic commands ###
