"""empty message

Revision ID: 6e84670c6704
Revises: f2fdd94e436a
Create Date: 2020-04-01 14:30:47.175264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e84670c6704'
down_revision = 'f2fdd94e436a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournaments', sa.Column('external_url', sa.String(length=120), nullable=True))
    op.drop_column('tournaments', 'external_link')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournaments', sa.Column('external_link', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_column('tournaments', 'external_url')
    # ### end Alembic commands ###
