"""empty message

Revision ID: 6fb82bbad8f6
Revises: b3470a9431db
Create Date: 2018-05-17 00:02:01.363065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fb82bbad8f6'
down_revision = 'b3470a9431db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('match_string', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'match_string')
    # ### end Alembic commands ###
