"""empty message

Revision ID: 76510d9e9453
Revises: 65ec6912bc6a
Create Date: 2021-02-10 21:25:29.740723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76510d9e9453'
down_revision = '65ec6912bc6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games_all', sa.Column('janus_room', sa.Integer(), nullable=True))
    op.create_unique_constraint(op.f('uq_games_all_janus_room'), 'games_all', ['janus_room'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_games_all_janus_room'), 'games_all', type_='unique')
    op.drop_column('games_all', 'janus_room')
    # ### end Alembic commands ###
