"""empty message

Revision ID: 7df519023d38
Revises: bc8fb2500eab
Create Date: 2020-03-27 14:55:17.285493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7df519023d38'
down_revision = 'bc8fb2500eab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_settings', sa.Column('notification_sound', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_settings', 'notification_sound')
    # ### end Alembic commands ###
