"""empty message

Revision ID: 858c1d4d61a9
Revises: 960ddaaedd7a
Create Date: 2020-05-18 17:17:25.848786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '858c1d4d61a9'
down_revision = '960ddaaedd7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournament_games', sa.Column('match_is_bye', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tournament_games', 'match_is_bye')
    # ### end Alembic commands ###
