"""empty message

Revision ID: 8cfc90667c26
Revises: f6b2165d7db2
Create Date: 2018-06-13 21:50:07.975867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cfc90667c26'
down_revision = 'f6b2165d7db2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('type', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notifications', 'type')
    # ### end Alembic commands ###
