"""empty message

Revision ID: 9043552aa43c
Revises: 6fb82bbad8f6
Create Date: 2018-05-17 00:29:17.019128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9043552aa43c'
down_revision = '6fb82bbad8f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('match_json', sa.JSON(), nullable=True))
    op.drop_column('games', 'match_string')
    op.drop_column('games', 'player1_next_turn')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('player1_next_turn', sa.BOOLEAN(), nullable=True))
    op.add_column('games', sa.Column('match_string', sa.TEXT(), nullable=True))
    op.drop_column('games', 'match_json')
    # ### end Alembic commands ###
