"""empty message

Revision ID: 937d87e4b34e
Revises: 3767876f060a
Create Date: 2020-03-31 11:09:22.996250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '937d87e4b34e'
down_revision = '3767876f060a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournaments', sa.Column('note', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tournaments', 'note')
    # ### end Alembic commands ###
