"""empty message

Revision ID: 9b39e3bac5af
Revises: 46527561d02c
Create Date: 2020-04-07 21:58:14.801635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b39e3bac5af'
down_revision = '46527561d02c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_version', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_version')
    # ### end Alembic commands ###
