"""empty message

Revision ID: a7df08ad4b96
Revises: 594808340e89
Create Date: 2020-05-16 11:17:33.580968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7df08ad4b96'
down_revision = '594808340e89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tournament_games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('tournament_stage_game_id', sa.Integer(), nullable=True),
    sa.Column('tournament_stage_game_bracket_id', sa.Integer(), nullable=True),
    sa.Column('tournament_round_id', sa.Integer(), nullable=True),
    sa.Column('winner_id', sa.Integer(), nullable=True),
    sa.Column('loser_id', sa.Integer(), nullable=True),
    sa.Column('p1_winner_from_id', sa.Integer(), nullable=True),
    sa.Column('p2_winner_from_id', sa.Integer(), nullable=True),
    sa.Column('p1_loser_from_id', sa.Integer(), nullable=True),
    sa.Column('p2_loser_from_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games_all.id'], name=op.f('fk_tournament_games_game_id_games_all')),
    sa.ForeignKeyConstraint(['loser_id'], ['users.id'], name=op.f('fk_tournament_games_loser_id_users')),
    sa.ForeignKeyConstraint(['p1_loser_from_id'], ['tournament_games.id'], name=op.f('fk_tournament_games_p1_loser_from_id_tournament_games')),
    sa.ForeignKeyConstraint(['p1_winner_from_id'], ['tournament_games.id'], name=op.f('fk_tournament_games_p1_winner_from_id_tournament_games')),
    sa.ForeignKeyConstraint(['p2_loser_from_id'], ['tournament_games.id'], name=op.f('fk_tournament_games_p2_loser_from_id_tournament_games')),
    sa.ForeignKeyConstraint(['p2_winner_from_id'], ['tournament_games.id'], name=op.f('fk_tournament_games_p2_winner_from_id_tournament_games')),
    sa.ForeignKeyConstraint(['tournament_round_id'], ['tournament_stage_rounds.id'], name=op.f('fk_tournament_games_tournament_round_id_tournament_stage_rounds')),
    sa.ForeignKeyConstraint(['winner_id'], ['users.id'], name=op.f('fk_tournament_games_winner_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tournament_games'))
    )
    op.add_column('games_all', sa.Column('tournament_game_id', sa.Integer(), nullable=True))
    op.drop_constraint('fk_games_all_tournament_round_id_tournament_stage_rounds', 'games_all', type_='foreignkey')
    op.create_foreign_key(op.f('fk_games_all_tournament_game_id_tournament_games'), 'games_all', 'tournament_games', ['tournament_game_id'], ['id'])
    op.drop_column('games_all', 'tournament_stage_game_id')
    op.drop_column('games_all', 'tournament_round_id')
    op.drop_column('games_all', 'tournament_stage_game_bracket_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games_all', sa.Column('tournament_stage_game_bracket_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('games_all', sa.Column('tournament_round_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('games_all', sa.Column('tournament_stage_game_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(op.f('fk_games_all_tournament_game_id_tournament_games'), 'games_all', type_='foreignkey')
    op.create_foreign_key('fk_games_all_tournament_round_id_tournament_stage_rounds', 'games_all', 'tournament_stage_rounds', ['tournament_round_id'], ['id'])
    op.drop_column('games_all', 'tournament_game_id')
    op.drop_table('tournament_games')
    # ### end Alembic commands ###
