"""empty message

Revision ID: abaef29d6ab4
Revises: 9f8355316c4d
Create Date: 2020-03-28 19:22:32.637270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abaef29d6ab4'
down_revision = '9f8355316c4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('public_challenge', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'public_challenge')
    # ### end Alembic commands ###
