"""empty message

Revision ID: ac29765971b6
Revises: f982972b7d11
Create Date: 2020-04-09 19:21:00.813702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac29765971b6'
down_revision = 'f982972b7d11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('jitsi_hashid', sa.String(length=10), nullable=True))
    op.add_column('games', sa.Column('webcam', sa.Boolean(), nullable=True))
    op.create_unique_constraint(op.f('uq_games_jitsi_hashid'), 'games', ['jitsi_hashid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_games_jitsi_hashid'), 'games', type_='unique')
    op.drop_column('games', 'webcam')
    op.drop_column('games', 'jitsi_hashid')
    # ### end Alembic commands ###
