"""empty message

Revision ID: b02d504627a2
Revises: 3852985df9fd
Create Date: 2018-05-18 00:20:34.976786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b02d504627a2'
down_revision = '3852985df9fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('in_mode', sa.String(length=15), nullable=True))
    op.add_column('games', sa.Column('out_mode', sa.String(length=15), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'out_mode')
    op.drop_column('games', 'in_mode')
    # ### end Alembic commands ###
