"""empty message

Revision ID: b16cbb70839c
Revises: 1507255054e5
Create Date: 2021-02-10 22:31:08.960960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b16cbb70839c'
down_revision = '1507255054e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_games_all_janus_room'), 'games_all', ['janus_room'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_games_all_janus_room'), 'games_all', type_='unique')
    # ### end Alembic commands ###
