"""empty message

Revision ID: b3470a9431db
Revises: 4ea89fe9b402
Create Date: 2018-05-16 23:49:38.307416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3470a9431db'
down_revision = '4ea89fe9b402'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('player1_next_turn', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'player1_next_turn')
    # ### end Alembic commands ###
