"""empty message

Revision ID: b6f5de8a6bb0
Revises: 6b9bed83861a
Create Date: 2020-04-14 11:00:49.608398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6f5de8a6bb0'
down_revision = '6b9bed83861a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('webcam_settings', sa.Column('force_scoreboard_page', sa.Boolean(), nullable=True))
    op.add_column('webcam_settings', sa.Column('mobile_app', sa.Boolean(), nullable=True))
    op.drop_column('webcam_settings', 'flip_preview')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('webcam_settings', sa.Column('flip_preview', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('webcam_settings', 'mobile_app')
    op.drop_column('webcam_settings', 'force_scoreboard_page')
    # ### end Alembic commands ###
