"""empty message

Revision ID: bc8fb2500eab
Revises: 3057cf5dd2be
Create Date: 2020-03-26 19:35:11.638896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc8fb2500eab'
down_revision = '3057cf5dd2be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_settings',
    sa.Column('user', sa.Integer(), nullable=False),
    sa.Column('match_alerts', sa.Boolean(), nullable=True),
    sa.Column('allow_challenges', sa.Boolean(), nullable=True),
    sa.Column('allow_private_messages', sa.Boolean(), nullable=True),
    sa.Column('allow_friend_requests', sa.Boolean(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user'], ['users.id'], name=op.f('fk_user_settings_user_users')),
    sa.PrimaryKeyConstraint('user', name=op.f('pk_user_settings'))
    )
    op.create_table('x01_presettings',
    sa.Column('user', sa.Integer(), nullable=False),
    sa.Column('bo_sets', sa.Integer(), nullable=True),
    sa.Column('bo_legs', sa.Integer(), nullable=True),
    sa.Column('two_clear_legs', sa.Boolean(), nullable=True),
    sa.Column('starter', sa.String(length=25), nullable=True),
    sa.Column('type', sa.Integer(), nullable=True),
    sa.Column('in_mode', sa.String(length=15), nullable=True),
    sa.Column('out_mode', sa.String(length=15), nullable=True),
    sa.Column('opponent_type', sa.String(length=10), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user'], ['users.id'], name=op.f('fk_x01_presettings_user_users')),
    sa.PrimaryKeyConstraint('user', name=op.f('pk_x01_presettings'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('x01_presettings')
    op.drop_table('user_settings')
    # ### end Alembic commands ###
