"""empty message

Revision ID: bea8717783db
Revises: 077302ba7c7e
Create Date: 2019-01-08 13:48:56.747651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bea8717783db'
down_revision = '077302ba7c7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('cpu_delay', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'cpu_delay')
    # ### end Alembic commands ###
