"""empty message

Revision ID: c099aa1d45f7
Revises: ecb4c2e445df
Create Date: 2019-12-06 17:46:40.698912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c099aa1d45f7'
down_revision = 'ecb4c2e445df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games_cricket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hashid', sa.String(length=10), nullable=True),
    sa.Column('bo_sets', sa.Integer(), nullable=False),
    sa.Column('bo_legs', sa.Integer(), nullable=False),
    sa.Column('two_clear_legs', sa.Boolean(), nullable=True),
    sa.Column('p1_sets', sa.Integer(), nullable=True),
    sa.Column('p2_sets', sa.Integer(), nullable=True),
    sa.Column('p1_legs', sa.Integer(), nullable=True),
    sa.Column('p2_legs', sa.Integer(), nullable=True),
    sa.Column('p1_next_turn', sa.Boolean(), nullable=True),
    sa.Column('closest_to_bull', sa.Boolean(), nullable=True),
    sa.Column('closest_to_bull_json', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('match_json', sa.JSON(), nullable=True),
    sa.Column('begin', sa.DateTime(), nullable=True),
    sa.Column('end', sa.DateTime(), nullable=True),
    sa.Column('opponent_type', sa.String(length=10), nullable=True),
    sa.Column('player1', sa.Integer(), nullable=True),
    sa.Column('player2', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['player1'], ['users.id'], name=op.f('fk_games_cricket_player1_users')),
    sa.ForeignKeyConstraint(['player2'], ['users.id'], name=op.f('fk_games_cricket_player2_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_games_cricket')),
    sa.UniqueConstraint('hashid', name=op.f('uq_games_cricket_hashid'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('games_cricket')
    # ### end Alembic commands ###
