"""empty message

Revision ID: c0a31cca0e11
Revises: 347a1c54005d
Create Date: 2020-04-01 18:57:56.232533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0a31cca0e11'
down_revision = '347a1c54005d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_chatmessages_ingame_game_hashid'), 'chatmessages_ingame', ['game_hashid'], unique=False)
    op.create_index(op.f('ix_notifications_user'), 'notifications', ['user'], unique=False)
    op.create_index(op.f('ix_user_statistic_user'), 'user_statistic', ['user'], unique=True)
    op.drop_constraint('uq_user_statistic_user', 'user_statistic', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_user_statistic_user', 'user_statistic', ['user'])
    op.drop_index(op.f('ix_user_statistic_user'), table_name='user_statistic')
    op.drop_index(op.f('ix_notifications_user'), table_name='notifications')
    op.drop_index(op.f('ix_chatmessages_ingame_game_hashid'), table_name='chatmessages_ingame')
    # ### end Alembic commands ###
