"""empty message

Revision ID: c5015c06a737
Revises: ecb4c2e445df
Create Date: 2020-03-20 15:21:52.412100

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c5015c06a737'
down_revision = 'ecb4c2e445df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_statistic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.Column('average', sa.Float(), nullable=True),
    sa.Column('doubles', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user'], ['users.id'], name=op.f('fk_user_statistic_user_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_statistic'))
    )
    op.drop_table('games_cricket')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games_cricket',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('hashid', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('bo_sets', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('bo_legs', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('two_clear_legs', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('p1_sets', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('p2_sets', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('p1_legs', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('p2_legs', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('p1_next_turn', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('closest_to_bull', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('closest_to_bull_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('match_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('begin', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('end', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('opponent_type', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('player1', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('player2', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['player1'], ['users.id'], name='fk_games_cricket_player1_users'),
    sa.ForeignKeyConstraint(['player2'], ['users.id'], name='fk_games_cricket_player2_users'),
    sa.PrimaryKeyConstraint('id', name='pk_games_cricket'),
    sa.UniqueConstraint('hashid', name='uq_games_cricket_hashid')
    )
    op.drop_table('user_statistic')
    # ### end Alembic commands ###
