"""empty message

Revision ID: d186a43f11cf
Revises: 19fd30207669
Create Date: 2020-03-24 20:52:35.448210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd186a43f11cf'
down_revision = '19fd30207669'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_statistic', sa.Column('darts_thrown', sa.Integer(), nullable=True))
    op.add_column('user_statistic', sa.Column('first9', sa.Float(), nullable=True))
    op.add_column('user_statistic', sa.Column('total_games', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_statistic', 'total_games')
    op.drop_column('user_statistic', 'first9')
    op.drop_column('user_statistic', 'darts_thrown')
    # ### end Alembic commands ###
