"""empty message

Revision ID: d1c9d86192cb
Revises: e2741c737135
Create Date: 2018-05-22 09:28:53.549188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1c9d86192cb'
down_revision = 'e2741c737135'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hashid', sa.String(length=10), nullable=True),
    sa.Column('player1', sa.Integer(), nullable=True),
    sa.Column('player2', sa.Integer(), nullable=True),
    sa.Column('bo_sets', sa.Integer(), nullable=False),
    sa.Column('bo_legs', sa.Integer(), nullable=False),
    sa.Column('p1_sets', sa.Integer(), nullable=True),
    sa.Column('p2_sets', sa.Integer(), nullable=True),
    sa.Column('p1_legs', sa.Integer(), nullable=True),
    sa.Column('p2_legs', sa.Integer(), nullable=True),
    sa.Column('p1_score', sa.Integer(), nullable=True),
    sa.Column('p2_score', sa.Integer(), nullable=True),
    sa.Column('p1_next_turn', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('type', sa.Integer(), nullable=True),
    sa.Column('match_json', sa.JSON(), nullable=True),
    sa.Column('in_mode', sa.String(length=15), nullable=True),
    sa.Column('out_mode', sa.String(length=15), nullable=True),
    sa.Column('begin', sa.DateTime(), nullable=True),
    sa.Column('end', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['player1'], ['users.id'], ),
    sa.ForeignKeyConstraint(['player2'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hashid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('games')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
