"""empty message

Revision ID: d28336dba58f
Revises: c5ab287856d6
Create Date: 2020-04-14 16:24:32.913353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd28336dba58f'
down_revision = 'c5ab287856d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_settings', sa.Column('channel_id', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_settings', 'channel_id')
    # ### end Alembic commands ###
