"""empty message

Revision ID: d376c386d25b
Revises: 4b8ff246769c
Create Date: 2020-04-03 10:38:37.284577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd376c386d25b'
down_revision = '4b8ff246769c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('alternative_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_users_alternative_id'), 'users', ['alternative_id'], unique=True)
    op.drop_index('ix_users_hashid', table_name='users')
    op.drop_column('users', 'hashid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hashid', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.create_index('ix_users_hashid', 'users', ['hashid'], unique=True)
    op.drop_index(op.f('ix_users_alternative_id'), table_name='users')
    op.drop_column('users', 'alternative_id')
    # ### end Alembic commands ###
