"""empty message

Revision ID: d5618c2750b1
Revises: e20ae2638e7c
Create Date: 2018-05-21 18:27:13.003929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5618c2750b1'
down_revision = 'e20ae2638e7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('started', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'started')
    # ### end Alembic commands ###
