"""empty message

Revision ID: d98eccfc90ca
Revises: 3ed8522baebc
Create Date: 2020-05-06 17:53:19.303151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd98eccfc90ca'
down_revision = '3ed8522baebc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stream_game', sa.Column('user', sa.Integer(), nullable=False))
    op.create_foreign_key(op.f('fk_stream_game_user_users'), 'stream_game', 'users', ['user'], ['id'])
    op.add_column('tournaments', sa.Column('api_key', sa.String(length=16), nullable=True))
    op.add_column('users', sa.Column('api_key', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'api_key')
    op.drop_column('tournaments', 'api_key')
    op.drop_constraint(op.f('fk_stream_game_user_users'), 'stream_game', type_='foreignkey')
    op.drop_column('stream_game', 'user')
    # ### end Alembic commands ###
