"""empty message

Revision ID: dead67a372b5
Revises: 937d87e4b34e
Create Date: 2020-03-31 11:49:19.180138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dead67a372b5'
down_revision = '937d87e4b34e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournaments', sa.Column('description', sa.String(length=200), nullable=True))
    op.drop_column('tournaments', 'note')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournaments', sa.Column('note', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.drop_column('tournaments', 'description')
    # ### end Alembic commands ###
