"""empty message

Revision ID: e20ae2638e7c
Revises: 39073935c873
Create Date: 2018-05-18 17:29:02.208323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e20ae2638e7c'
down_revision = '39073935c873'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('begin', sa.DateTime(), nullable=True))
    op.add_column('games', sa.Column('end', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'end')
    op.drop_column('games', 'begin')
    # ### end Alembic commands ###
