"""empty message

Revision ID: e2741c737135
Revises: d5618c2750b1
Create Date: 2018-05-21 19:49:28.449398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2741c737135'
down_revision = 'd5618c2750b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('status', sa.String(length=20), nullable=True))
    op.drop_column('games', 'started')
    op.drop_column('games', 'completed')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('completed', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('games', sa.Column('started', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('games', 'status')
    # ### end Alembic commands ###
