"""empty message

Revision ID: e9bce18a545f
Revises: 9043552aa43c
Create Date: 2018-05-17 09:30:10.748321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9bce18a545f'
down_revision = '9043552aa43c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('bo_legs', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('bo_sets', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('p1_legs', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('p1_score', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('p1_sets', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('p2_legs', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('p2_score', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('p2_sets', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'p2_sets')
    op.drop_column('games', 'p2_score')
    op.drop_column('games', 'p2_legs')
    op.drop_column('games', 'p1_sets')
    op.drop_column('games', 'p1_score')
    op.drop_column('games', 'p1_legs')
    op.drop_column('games', 'bo_sets')
    op.drop_column('games', 'bo_legs')
    # ### end Alembic commands ###
