"""empty message

Revision ID: ecb4c2e445df
Revises: 37ac7bd96038
Create Date: 2019-07-09 16:25:05.701596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecb4c2e445df'
down_revision = '37ac7bd96038'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('two_clear_legs', sa.Boolean(), nullable=True))
    op.create_unique_constraint(op.f('uq_games_hashid'), 'games', ['hashid'])
    op.drop_constraint('games_hashid_key', 'games', type_='unique')
    op.create_unique_constraint(op.f('uq_roles_name'), 'roles', ['name'])
    op.drop_constraint('roles_name_key', 'roles', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('roles_name_key', 'roles', ['name'])
    op.drop_constraint(op.f('uq_roles_name'), 'roles', type_='unique')
    op.create_unique_constraint('games_hashid_key', 'games', ['hashid'])
    op.drop_constraint(op.f('uq_games_hashid'), 'games', type_='unique')
    op.drop_column('games', 'two_clear_legs')
    # ### end Alembic commands ###
