"""empty message

Revision ID: ed681f762e01
Revises: 100d0a3abe51
Create Date: 2020-04-05 17:31:29.871921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed681f762e01'
down_revision = '100d0a3abe51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_settings', sa.Column('profile_text', sa.String(length=2000), nullable=True))
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_verified')
    op.drop_column('user_settings', 'profile_text')
    # ### end Alembic commands ###
