"""empty message

Revision ID: f2fdd94e436a
Revises: 
Create Date: 2020-04-01 13:42:33.164142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2fdd94e436a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('fk_games_tournament_tournaments'), 'games', 'tournaments', ['tournament'], ['hashid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_games_tournament_tournaments'), 'games', type_='foreignkey')
    # ### end Alembic commands ###
