"""empty message

Revision ID: f6b2165d7db2
Revises: cedbc1df6c54
Create Date: 2018-06-13 21:08:58.665361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6b2165d7db2'
down_revision = 'cedbc1df6c54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('author', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notifications', 'author')
    # ### end Alembic commands ###
