"""empty message

Revision ID: f7e302692d50
Revises: d78373a0105f
Create Date: 2018-05-30 13:55:56.335253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7e302692d50'
down_revision = 'd78373a0105f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friendship_requests',
    sa.Column('requesting_user_id', sa.Integer(), nullable=False),
    sa.Column('receiving_user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['receiving_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['requesting_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('requesting_user_id', 'receiving_user_id')
    )
    op.create_table('friendships',
    sa.Column('user1_id', sa.Integer(), nullable=False),
    sa.Column('user2_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user1_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user2_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user1_id', 'user2_id')
    )
    op.drop_table('relationships')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('relationships',
    sa.Column('requesting_user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('receiving_user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=15), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['receiving_user_id'], ['users.id'], name='relationships_receiving_user_id_fkey'),
    sa.ForeignKeyConstraint(['requesting_user_id'], ['users.id'], name='relationships_requesting_user_id_fkey'),
    sa.PrimaryKeyConstraint('requesting_user_id', 'receiving_user_id', name='relationships_pkey')
    )
    op.drop_table('friendships')
    op.drop_table('friendship_requests')
    # ### end Alembic commands ###
