"""empty message

Revision ID: f982972b7d11
Revises: 9b39e3bac5af
Create Date: 2020-04-08 12:41:32.798244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f982972b7d11'
down_revision = '9b39e3bac5af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('score_input_delay', sa.Integer(), nullable=True))
    op.add_column('x01_presettings', sa.Column('score_input_delay', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('x01_presettings', 'score_input_delay')
    op.drop_column('games', 'score_input_delay')
    # ### end Alembic commands ###
