"""empty message

Revision ID: fc0e6cec849f
Revises: 858c1d4d61a9
Create Date: 2020-05-21 13:18:56.270456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc0e6cec849f'
down_revision = '858c1d4d61a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tournament_games', sa.Column('p1_ready', sa.Boolean(), server_default='f', nullable=True))
    op.add_column('tournament_games', sa.Column('p2_ready', sa.Boolean(), server_default='f', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tournament_games', 'p2_ready')
    op.drop_column('tournament_games', 'p1_ready')
    # ### end Alembic commands ###
