"""empty message

Revision ID: fcb4a534aa37
Revises: 65ec6912bc6a
Create Date: 2020-05-14 14:15:12.276738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcb4a534aa37'
down_revision = '65ec6912bc6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tournament_applications_association',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], name=op.f('fk_tournament_applications_association_tournament_id_tournaments')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_tournament_applications_association_user_id_users')),
    sa.PrimaryKeyConstraint('user_id', 'tournament_id', name=op.f('pk_tournament_applications_association'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tournament_applications_association')
    # ### end Alembic commands ###
